### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by fadookie** [jordfocus/Custom-Radial-Progress#1]
Thanks for this sample! I'm gonna see if I can use this as a starting point for implementing an iOS renderer as well. If I succeed I might send a pull request if the bossman okays it :)

Could you please add an open-source license to this project so that I can be sure it's okay to use in a commercial project? Something like MIT, BSD, or Apache would be great.

Thanks!

**Comment by j0rdan-dev** [comment]
Thank you for your comment, I've added MIT license. I hope your bossman will okays it :)
I'm looking forward to see how the implementation of the iOS renderer will go. If you run into some troubles don't hesitate to contact me :)

Regards,
Jordan
